/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Helper.DialogHelper;
import Helper.ShareHelper;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Quy Bong
 */
public class quanly extends javax.swing.JFrame {

    /**
     * Creates new form quanly
     */
    public quanly() {
        initComponents();
    }

    void exit() {

        if (DialogHelper.confirm(this, "Bạn thực sự muốn kết thúc?")) {
            System.exit(0);
        }
    }    

    void openNguoiHoc() {
        if (ShareHelper.authenticated()) {

            new NguoiHocJdialog().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnnguoihoc = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnhethong = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        mnidoimk = new javax.swing.JMenuItem();
        mniketthuc = new javax.swing.JMenuItem();
        mnquanly = new javax.swing.JMenu();
        mninguoihoc = new javax.swing.JMenuItem();
        mnichuyende = new javax.swing.JMenuItem();
        mnikhoahoc = new javax.swing.JMenuItem();
        mninhanvien = new javax.swing.JMenuItem();
        mnthongke = new javax.swing.JMenu();
        mninguoihoctungnam = new javax.swing.JMenuItem();
        mnibangdiemtungkhoa = new javax.swing.JMenuItem();
        mnidiemtungkhoa = new javax.swing.JMenuItem();
        mnidoanhthu = new javax.swing.JMenuItem();
        mntrogiup = new javax.swing.JMenu();
        mnihuongdan = new javax.swing.JMenuItem();
        mnigioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/Exit.png"))); // NOI18N
        jButton1.setText(" đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/Stop.png"))); // NOI18N
        jButton2.setText("kết thúc");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/Task list.png"))); // NOI18N
        jButton3.setText("chuyên đề");

        btnnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/List.png"))); // NOI18N
        btnnguoihoc.setText("người học");
        btnnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoihocActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/Address book.png"))); // NOI18N
        jButton5.setText("khóa học");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/Favourites.png"))); // NOI18N
        jButton6.setText("hướng dẫn");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/fpt.png"))); // NOI18N

        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Hinh/Alarm.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        mnhethong.setText("Hệ thống");

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnidangnhap.setText("Đăng nhập");
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        mnhethong.add(mnidangnhap);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnidangxuat.setText("Đăng xuất");
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        mnhethong.add(mnidangxuat);

        mnidoimk.setText("Đổi mật khẩu");
        mnhethong.add(mnidoimk);

        mniketthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniketthuc.setText("Kết thúc");
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        mnhethong.add(mniketthuc);

        jMenuBar1.add(mnhethong);

        mnquanly.setText("Quản lý");

        mninguoihoc.setText("Người học");
        mninguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninguoihocActionPerformed(evt);
            }
        });
        mnquanly.add(mninguoihoc);

        mnichuyende.setText("Chuyên đề");
        mnichuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnichuyendeActionPerformed(evt);
            }
        });
        mnquanly.add(mnichuyende);

        mnikhoahoc.setText("Khóa học");
        mnikhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikhoahocActionPerformed(evt);
            }
        });
        mnquanly.add(mnikhoahoc);

        mninhanvien.setText("Nhân viên");
        mninhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninhanvienActionPerformed(evt);
            }
        });
        mnquanly.add(mninhanvien);

        jMenuBar1.add(mnquanly);

        mnthongke.setText("Thống kê");

        mninguoihoctungnam.setText("Người học từng năm");
        mninguoihoctungnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninguoihoctungnamActionPerformed(evt);
            }
        });
        mnthongke.add(mninguoihoctungnam);

        mnibangdiemtungkhoa.setText("Bảng điểm từng khóa");
        mnibangdiemtungkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibangdiemtungkhoaActionPerformed(evt);
            }
        });
        mnthongke.add(mnibangdiemtungkhoa);

        mnidiemtungkhoa.setText("Điểm từng khóa học");
        mnidiemtungkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidiemtungkhoaActionPerformed(evt);
            }
        });
        mnthongke.add(mnidiemtungkhoa);

        mnidoanhthu.setText("Doanh thu từng chuyên đề");
        mnidoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoanhthuActionPerformed(evt);
            }
        });
        mnthongke.add(mnidoanhthu);

        jMenuBar1.add(mnthongke);

        mntrogiup.setText("Trợ giúp");

        mnihuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnihuongdan.setText("Hướng dẫn sử dụng");
        mntrogiup.add(mnihuongdan);

        mnigioithieu.setText("Giới thiệu sản phẩm");
        mntrogiup.add(mnigioithieu);

        jMenuBar1.add(mntrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(2, 2, 2)
                        .addComponent(jButton2)
                        .addGap(1, 1, 1)
                        .addComponent(jButton3)
                        .addGap(2, 2, 2)
                        .addComponent(btnnguoihoc)
                        .addGap(1, 1, 1)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbldongho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnnguoihoc)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton3)
                        .addComponent(jButton2)))
                .addGap(136, 136, 136)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
     
       // TODO add your handling code here:
    }//GEN-LAST:event_mnidangnhapActionPerformed

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_mniketthucActionPerformed

    private void mninguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninguoihocActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_mninguoihocActionPerformed

    private void mnichuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnichuyendeActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_mnichuyendeActionPerformed

    private void mnikhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikhoahocActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_mnikhoahocActionPerformed

    private void mninhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninhanvienActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mninhanvienActionPerformed

    private void mninguoihoctungnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninguoihoctungnamActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_mninguoihoctungnamActionPerformed

    private void mnibangdiemtungkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibangdiemtungkhoaActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_mnibangdiemtungkhoaActionPerformed

    private void mnidiemtungkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidiemtungkhoaActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_mnidiemtungkhoaActionPerformed

    private void mnidoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoanhthuActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_mnidoanhthuActionPerformed

    private void btnnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoihocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
    }//GEN-LAST:event_btnnguoihocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnguoihoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenu mnhethong;
    private javax.swing.JMenuItem mnibangdiemtungkhoa;
    private javax.swing.JMenuItem mnichuyende;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidiemtungkhoa;
    private javax.swing.JMenuItem mnidoanhthu;
    private javax.swing.JMenuItem mnidoimk;
    private javax.swing.JMenuItem mnigioithieu;
    private javax.swing.JMenuItem mnihuongdan;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenuItem mnikhoahoc;
    private javax.swing.JMenuItem mninguoihoc;
    private javax.swing.JMenuItem mninguoihoctungnam;
    private javax.swing.JMenuItem mninhanvien;
    private javax.swing.JMenu mnquanly;
    private javax.swing.JMenu mnthongke;
    private javax.swing.JMenu mntrogiup;
    // End of variables declaration//GEN-END:variables
}
